/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDesktopRouteImport } from './routes/auth/desktop'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiPolarWebhooksRouteImport } from './routes/api.polar.webhooks'
import { Route as ApiDownloadsSplatRouteImport } from './routes/api.downloads.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthedDashboardSecurityRouteImport } from './routes/_authed/dashboard/security'
import { Route as AuthedDashboardBillingRouteImport } from './routes/_authed/dashboard/billing'
import { Route as AuthedDashboardAdminRouteImport } from './routes/_authed/dashboard/admin'
import { Route as AuthedDashboardAccountRouteImport } from './routes/_authed/dashboard/account'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDesktopRoute = AuthDesktopRouteImport.update({
  id: '/auth/desktop',
  path: '/auth/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiPolarWebhooksRoute = ApiPolarWebhooksRouteImport.update({
  id: '/api/polar/webhooks',
  path: '/api/polar/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsSplatRoute = ApiDownloadsSplatRouteImport.update({
  id: '/api/downloads/$',
  path: '/api/downloads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSecurityRoute = AuthedDashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardBillingRoute = AuthedDashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardAdminRoute = AuthedDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardAccountRoute = AuthedDashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/auth/desktop': typeof AuthDesktopRoute
  '/dashboard/account': typeof AuthedDashboardAccountRoute
  '/dashboard/admin': typeof AuthedDashboardAdminRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$': typeof ApiDownloadsSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/auth/desktop': typeof AuthDesktopRoute
  '/dashboard/account': typeof AuthedDashboardAccountRoute
  '/dashboard/admin': typeof AuthedDashboardAdminRoute
  '/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$': typeof ApiDownloadsSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/auth/desktop': typeof AuthDesktopRoute
  '/_authed/dashboard/account': typeof AuthedDashboardAccountRoute
  '/_authed/dashboard/admin': typeof AuthedDashboardAdminRoute
  '/_authed/dashboard/billing': typeof AuthedDashboardBillingRoute
  '/_authed/dashboard/security': typeof AuthedDashboardSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$': typeof ApiDownloadsSplatRoute
  '/api/polar/webhooks': typeof ApiPolarWebhooksRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/download'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/waitlist'
    | '/dashboard'
    | '/auth/desktop'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/security'
    | '/api/auth/$'
    | '/api/downloads/$'
    | '/api/polar/webhooks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/download'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/waitlist'
    | '/auth/desktop'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/security'
    | '/api/auth/$'
    | '/api/downloads/$'
    | '/api/polar/webhooks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/changelog'
    | '/download'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/waitlist'
    | '/_authed/dashboard'
    | '/auth/desktop'
    | '/_authed/dashboard/account'
    | '/_authed/dashboard/admin'
    | '/_authed/dashboard/billing'
    | '/_authed/dashboard/security'
    | '/api/auth/$'
    | '/api/downloads/$'
    | '/api/polar/webhooks'
    | '/_authed/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  AuthDesktopRoute: typeof AuthDesktopRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadsSplatRoute: typeof ApiDownloadsSplatRoute
  ApiPolarWebhooksRoute: typeof ApiPolarWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/desktop': {
      id: '/auth/desktop'
      path: '/auth/desktop'
      fullPath: '/auth/desktop'
      preLoaderRoute: typeof AuthDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/polar/webhooks': {
      id: '/api/polar/webhooks'
      path: '/api/polar/webhooks'
      fullPath: '/api/polar/webhooks'
      preLoaderRoute: typeof ApiPolarWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads/$': {
      id: '/api/downloads/$'
      path: '/api/downloads/$'
      fullPath: '/api/downloads/$'
      preLoaderRoute: typeof ApiDownloadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/security': {
      id: '/_authed/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof AuthedDashboardSecurityRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/billing': {
      id: '/_authed/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthedDashboardBillingRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/admin': {
      id: '/_authed/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthedDashboardAdminRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/account': {
      id: '/_authed/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof AuthedDashboardAccountRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardAccountRoute: typeof AuthedDashboardAccountRoute
  AuthedDashboardAdminRoute: typeof AuthedDashboardAdminRoute
  AuthedDashboardBillingRoute: typeof AuthedDashboardBillingRoute
  AuthedDashboardSecurityRoute: typeof AuthedDashboardSecurityRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardAccountRoute: AuthedDashboardAccountRoute,
  AuthedDashboardAdminRoute: AuthedDashboardAdminRoute,
  AuthedDashboardBillingRoute: AuthedDashboardBillingRoute,
  AuthedDashboardSecurityRoute: AuthedDashboardSecurityRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  AuthDesktopRoute: AuthDesktopRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadsSplatRoute: ApiDownloadsSplatRoute,
  ApiPolarWebhooksRoute: ApiPolarWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
