/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewConnectionRouteImport } from './routes/new-connection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditConnectionConnectionIdRouteImport } from './routes/edit-connection.$connectionId'
import { Route as DbConnectionIdRouteImport } from './routes/db.$connectionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewConnectionRoute = NewConnectionRouteImport.update({
  id: '/new-connection',
  path: '/new-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditConnectionConnectionIdRoute =
  EditConnectionConnectionIdRouteImport.update({
    id: '/edit-connection/$connectionId',
    path: '/edit-connection/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DbConnectionIdRoute = DbConnectionIdRouteImport.update({
  id: '/db/$connectionId',
  path: '/db/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-connection': typeof NewConnectionRoute
  '/settings': typeof SettingsRoute
  '/db/$connectionId': typeof DbConnectionIdRoute
  '/edit-connection/$connectionId': typeof EditConnectionConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-connection': typeof NewConnectionRoute
  '/settings': typeof SettingsRoute
  '/db/$connectionId': typeof DbConnectionIdRoute
  '/edit-connection/$connectionId': typeof EditConnectionConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-connection': typeof NewConnectionRoute
  '/settings': typeof SettingsRoute
  '/db/$connectionId': typeof DbConnectionIdRoute
  '/edit-connection/$connectionId': typeof EditConnectionConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-connection'
    | '/settings'
    | '/db/$connectionId'
    | '/edit-connection/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-connection'
    | '/settings'
    | '/db/$connectionId'
    | '/edit-connection/$connectionId'
  id:
    | '__root__'
    | '/'
    | '/new-connection'
    | '/settings'
    | '/db/$connectionId'
    | '/edit-connection/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewConnectionRoute: typeof NewConnectionRoute
  SettingsRoute: typeof SettingsRoute
  DbConnectionIdRoute: typeof DbConnectionIdRoute
  EditConnectionConnectionIdRoute: typeof EditConnectionConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-connection': {
      id: '/new-connection'
      path: '/new-connection'
      fullPath: '/new-connection'
      preLoaderRoute: typeof NewConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-connection/$connectionId': {
      id: '/edit-connection/$connectionId'
      path: '/edit-connection/$connectionId'
      fullPath: '/edit-connection/$connectionId'
      preLoaderRoute: typeof EditConnectionConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$connectionId': {
      id: '/db/$connectionId'
      path: '/db/$connectionId'
      fullPath: '/db/$connectionId'
      preLoaderRoute: typeof DbConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewConnectionRoute: NewConnectionRoute,
  SettingsRoute: SettingsRoute,
  DbConnectionIdRoute: DbConnectionIdRoute,
  EditConnectionConnectionIdRoute: EditConnectionConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
